# Number of protections
death-protections-number: 10
default-added-protections-number: 0

# Does the game warn players when they have only a few protection opportunities left?
protect-warn:
  - 3
  - 1

# Message
protect-message: "§a玩家 §f{0} §a具有 §e{1}次 §a死亡保护§f,\n§a其中包含 §e{2}次 §a新人保护§f,§a以及 §e{3}次 §a的额外死亡保护§f."
protect-warn-message: "§a你只剩 §e{0}次 §a死亡保护了§f, \n§a其中新人保护仅剩 §e{1}次§f, §a额外死亡保护仅剩 §e{2}次§f."
death-message: "§a玩家 §f{0} §a已死亡：§e{1}次"
not-permission-message: "§c你没有使用该命令的权限！"
reload-message: "§a配置已重新加载!"
set-player-death-message: "§a已将玩家§f %s §a的死亡次数修改为:§e %d"
set-player-added-permission-message: "§a已将玩家§f %s §a的额外死亡保护次数修改为:§e %d次"
player-404-message: "§c玩家不存在或不在线"
value-err-message: "§c数值不合法"
set-added-protect-message: "§a已将玩家 §f{0} §a的额外死亡保护设为：§e{1}次"